### ISSUE TITLE
Great library!

### ISSUE THREAD

**Issue by Mihailoff** [ivandotv/estacion#167]
After researching a few event bus packages on npm, I have found this one and it looks clean and so far works great. Don't see too much of a community around it what is a bit concerning so I decided to open a ticket and see how it goes.

**Comment by ivandotv** [comment]
Thanks!
It's very hard for a package to gain traction on npm without any advertisements ( Reddit, hacker news, slack etc..). And also **event bus** pattern is not as prevalent in today's architecture as it used to be.
I have extracted this module from a much bigger application that was done for one of my clients, both front-end and back-end implementation.
It is actively maintained.

**Comment by Mihailoff** [comment]
Thank you for publishing the code and quick response. Off the topic, I've been to Novi Sad and visited the Petrovaradin Fortress, a wonderful city.

**Comment by ivandotv** [comment]
If you have any questions feel free to ask.
