### ISSUE TITLE
Multi-node environment

### ISSUE THREAD

**Issue by Mihailoff** [ivandotv/estacion#170]
As far as I can understand, this library works in a single-node environment -- an event triggered on one node won't reach other nodes.

Of course, there are other options from simple https://github.com/yss14/node-redis-eventbus to sophisticated https://github.com/socketio/socket.io. Just wondering what are your thoughts on this?

**Comment by ivandotv** [comment]
You are talking about some kind of microservice architecture, and this is out of scope for this library (and always will be). 
One way you can solve this is to have a `listener` on all `channels` and all `topics` who will relay all `events` to some outside process ( websocket , webhooks, etc), and on the other side (different node service/process/application) when you receive the event, then you use `Estacion` on that side to dispatch the event internally to all listeners.
On one of my client projects, I have made something like that, working via web sockets (client-server) communication. I am planning to release that code as a web socket library that standardizes the communication between the client and the server via channels and topics.
